CC = gcc
CFLAGS = -l readline
DEBUGFLAGS = -g
SOURCES = main.c
EXENAME = e
EXEDIR = build

default:
	$(CC) $(SOURCES) $(CFLAGS) -o $(EXEDIR)/$(EXENAME)

hex:
	$(CC) hexreader.c $(CFLAGS) -o $(EXEDIR)/hex